### PR TITLE
Some nice features for pf-formula 

### PR DESCRIPTION
**Pull request by marek-knappe**

### CODE REVIEW

**Comment by timniederhausen** [comment]
Hi, thanks for your contribution!
The unit test parts seem especially nice.

I have a question though:
It shouldn't be necessary to load `pf.ko` manually, as `/etc/rc.d/pf` already does that (by setting `required_modules` to `pf`). I just tested that on 10.3 and 11.2 and it works as expected.
How was that problem encountered?

**Comment by amontalban** [comment]
@timniederhausen the thing about loading `pf.ko` is because FreeBSD 11.2 needs to have it loaded.

Check http://freebsd.1045724.x6.nabble.com/Possible-bug-11-2-RELEASE-guest-with-vtnet-and-PF-td6266755.html.

BTW, please do not merge this yet as we have couple of other improvements on the way (pfsync/pflog) and other things.

Thanks!

**Comment by amontalban** [comment]
@timniederhausen ok we have finished with the PR (Sorry it got bigger than what we expected at first). If you have any question please ask @fzipi or me.

Thanks!

**Comment by timniederhausen** [comment]
This is very well done, I'll just merge this.

Thanks for all your work!

**Pull request merged**
